//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteBanHangEntities2 : DbContext
    {
        public WebsiteBanHangEntities2()
            : base("name=WebsiteBanHangEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C2119110263_Brand> C2119110263_Brand { get; set; }
        public virtual DbSet<C2119110263_Category> C2119110263_Category { get; set; }
        public virtual DbSet<C2119110263_Order> C2119110263_Order { get; set; }
        public virtual DbSet<C2119110263_Page> C2119110263_Page { get; set; }
        public virtual DbSet<C2119110263_Product> C2119110263_Product { get; set; }
        public virtual DbSet<C2119110263_Users> C2119110263_Users { get; set; }
        public virtual DbSet<C2119110263_OrderDetail> C2119110263_OrderDetail { get; set; }
    }
}
